/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.*;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Douglas
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private Divisao divisao; 
    private List<Divisao> divisoes;
    
    public JanelaPrincipal() { 
        divisoes = new ArrayList<Divisao>();
        divisao = new Divisao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelDepartamentos = new javax.swing.JPanel();
        labelDepartamentos = new javax.swing.JLabel();
        labelNomeDepartamento = new javax.swing.JLabel();
        comboBoxNomeDepartamento = new javax.swing.JComboBox();
        labelRecursosHumanos = new javax.swing.JLabel();
        textNomeRecursosHumanos = new javax.swing.JTextField();
        labelPrecoRH = new javax.swing.JLabel();
        textPrecoRH = new javax.swing.JTextField();
        labelNomeMaquina = new javax.swing.JLabel();
        textNomeMaquina = new javax.swing.JTextField();
        labelPrecoMaquina = new javax.swing.JLabel();
        textPrecoMaquina = new javax.swing.JTextField();
        labelNomeDoChefe = new javax.swing.JLabel();
        textNomeChefe = new javax.swing.JTextField();
        labelCustoChefe = new javax.swing.JLabel();
        textCustoChefe = new javax.swing.JTextField();
        labelBonificacao = new javax.swing.JLabel();
        textBonificacaoChefe = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonPesquisar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        botaAddDivisao = new javax.swing.JButton();
        panelRelatorioEEventos = new javax.swing.JPanel();
        labelSalarioRH = new javax.swing.JLabel();
        labelBonusChefe = new javax.swing.JLabel();
        textSalarioRH = new javax.swing.JTextField();
        textBonusChefe = new javax.swing.JTextField();
        buttonAjustarSalarioRH = new javax.swing.JButton();
        buttonAjustarBonusChefe = new javax.swing.JButton();
        labelExibirRelatorio = new javax.swing.JLabel();
        comboBoxExibirRelatorio = new javax.swing.JComboBox();
        buttonExibirRelatorio = new javax.swing.JButton();
        buttonExportarXml = new javax.swing.JButton();
        buttonImportarXml = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDepartamentos.setText("Departamentos");

        labelNomeDepartamento.setText("Nome do departamento:");

        comboBoxNomeDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxNomeDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNomeDepartamentoActionPerformed(evt);
            }
        });

        labelRecursosHumanos.setText("Nome do Recurso Humano:");

        labelPrecoRH.setText("Preço:");

        labelNomeMaquina.setText("Nome da máquina:");

        labelPrecoMaquina.setText("Preço:");

        labelNomeDoChefe.setText("Nome do chefe:");

        labelCustoChefe.setText("Custo:");

        labelBonificacao.setText("Bonificação:");

        buttonCadastrar.setText("Cadastrar");

        buttonAlterar.setText("Alterar");

        buttonPesquisar.setText("Pesquisar");

        buttonExcluir.setText("Excluir");

        botaAddDivisao.setText("Adicionar Divisao");
        botaAddDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaAddDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDepartamentosLayout = new javax.swing.GroupLayout(panelDepartamentos);
        panelDepartamentos.setLayout(panelDepartamentosLayout);
        panelDepartamentosLayout.setHorizontalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(labelDepartamentos))
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDepartamentosLayout.createSequentialGroup()
                                        .addComponent(labelNomeMaquina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeMaquina))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDepartamentosLayout.createSequentialGroup()
                                        .addComponent(labelRecursosHumanos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeRecursosHumanos))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDepartamentosLayout.createSequentialGroup()
                                        .addComponent(labelNomeDoChefe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNomeChefe)
                                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                                .addComponent(buttonCadastrar)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonAlterar)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonPesquisar)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)
                                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                                .addComponent(labelPrecoRH)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textPrecoRH))
                                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                                .addComponent(labelPrecoMaquina)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textPrecoMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                                .addComponent(labelCustoChefe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textCustoChefe)))
                                        .addGap(18, 18, 18)
                                        .addComponent(labelBonificacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textBonificacaoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buttonExcluir)))
                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                .addComponent(labelNomeDepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(botaAddDivisao)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDepartamentosLayout.setVerticalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDepartamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeDepartamento)
                    .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaAddDivisao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecursosHumanos)
                    .addComponent(textNomeRecursosHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoRH)
                    .addComponent(textPrecoRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeMaquina)
                    .addComponent(textNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoMaquina)
                    .addComponent(textPrecoMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeDoChefe)
                    .addComponent(textNomeChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustoChefe)
                    .addComponent(textCustoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBonificacao)
                    .addComponent(textBonificacaoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonPesquisar)
                    .addComponent(buttonExcluir))
                .addGap(25, 25, 25))
        );

        labelSalarioRH.setText("Salário(RH)           (%):");

        labelBonusChefe.setText("Bonus(Chefe)       (%):");

        buttonAjustarSalarioRH.setText("Ajustar Salário");

        buttonAjustarBonusChefe.setText("Ajustar Bônus");

        labelExibirRelatorio.setText("Exibir Relatório: ");

        comboBoxExibirRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonExibirRelatorio.setText("Exibir");

        buttonExportarXml.setText("Exportar XML");

        buttonImportarXml.setText("Importar XML");

        javax.swing.GroupLayout panelRelatorioEEventosLayout = new javax.swing.GroupLayout(panelRelatorioEEventos);
        panelRelatorioEEventos.setLayout(panelRelatorioEEventosLayout);
        panelRelatorioEEventosLayout.setHorizontalGroup(
            panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                        .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                                .addComponent(labelSalarioRH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSalarioRH, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                                .addComponent(labelBonusChefe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textBonusChefe)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAjustarSalarioRH)
                            .addComponent(buttonAjustarBonusChefe)))
                    .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                        .addComponent(labelExibirRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxExibirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExibirRelatorio))
                    .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                        .addComponent(buttonExportarXml)
                        .addGap(41, 41, 41)
                        .addComponent(buttonImportarXml)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRelatorioEEventosLayout.setVerticalGroup(
            panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioEEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalarioRH)
                    .addComponent(textSalarioRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAjustarSalarioRH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBonusChefe)
                    .addComponent(textBonusChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAjustarBonusChefe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExibirRelatorio)
                    .addComponent(comboBoxExibirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExibirRelatorio))
                .addGap(49, 49, 49)
                .addGroup(panelRelatorioEEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExportarXml)
                    .addComponent(buttonImportarXml))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRelatorioEEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRelatorioEEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxNomeDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNomeDepartamentoActionPerformed
        
    }//GEN-LAST:event_comboBoxNomeDepartamentoActionPerformed

    private void botaAddDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaAddDivisaoActionPerformed
       new gui.JanelaAdicionarDivisao().setVisible(true);
    }//GEN-LAST:event_botaAddDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaAddDivisao;
    private javax.swing.JButton buttonAjustarBonusChefe;
    private javax.swing.JButton buttonAjustarSalarioRH;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonExibirRelatorio;
    private javax.swing.JButton buttonExportarXml;
    private javax.swing.JButton buttonImportarXml;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JComboBox comboBoxExibirRelatorio;
    private javax.swing.JComboBox comboBoxNomeDepartamento;
    private javax.swing.JLabel labelBonificacao;
    private javax.swing.JLabel labelBonusChefe;
    private javax.swing.JLabel labelCustoChefe;
    private javax.swing.JLabel labelDepartamentos;
    private javax.swing.JLabel labelExibirRelatorio;
    private javax.swing.JLabel labelNomeDepartamento;
    private javax.swing.JLabel labelNomeDoChefe;
    private javax.swing.JLabel labelNomeMaquina;
    private javax.swing.JLabel labelPrecoMaquina;
    private javax.swing.JLabel labelPrecoRH;
    private javax.swing.JLabel labelRecursosHumanos;
    private javax.swing.JLabel labelSalarioRH;
    private javax.swing.JPanel panelDepartamentos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRelatorioEEventos;
    private javax.swing.JTextField textBonificacaoChefe;
    private javax.swing.JTextField textBonusChefe;
    private javax.swing.JTextField textCustoChefe;
    private javax.swing.JTextField textNomeChefe;
    private javax.swing.JTextField textNomeMaquina;
    private javax.swing.JTextField textNomeRecursosHumanos;
    private javax.swing.JTextField textPrecoMaquina;
    private javax.swing.JTextField textPrecoRH;
    private javax.swing.JTextField textSalarioRH;
    // End of variables declaration//GEN-END:variables
}
