/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Douglas
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private Divisao divisao;
    private Maquinas maquina;
    private RecursosHumanos rh;
    private Chefe chefe;
    private List<Divisao> divisoes;
    private IteratorVisitor iterator;
    public JanelaPrincipal() { 
        divisoes = new ArrayList<Divisao>();
        divisao = new Divisao();
        maquina = new Maquinas();
        rh = new RecursosHumanos();
        chefe = new Chefe();
        iterator = new IteratorVisitor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelDepartamentos = new javax.swing.JPanel();
        labelNomeDivisao = new javax.swing.JLabel();
        comboBoxNomeDivisao = new javax.swing.JComboBox();
        labelRecursosHumanos = new javax.swing.JLabel();
        textNomeRecursosHumanos = new javax.swing.JTextField();
        labelPrecoRH = new javax.swing.JLabel();
        textPrecoRH = new javax.swing.JTextField();
        labelNomeMaquina = new javax.swing.JLabel();
        textNomeMaquina = new javax.swing.JTextField();
        labelPrecoMaquina = new javax.swing.JLabel();
        textPrecoMaquina = new javax.swing.JTextField();
        labelNomeDoChefe = new javax.swing.JLabel();
        textNomeChefe = new javax.swing.JTextField();
        labelCustoChefe = new javax.swing.JLabel();
        textCustoChefe = new javax.swing.JTextField();
        labelBonificacao = new javax.swing.JLabel();
        textBonificacaoChefe = new javax.swing.JTextField();
        botaAddDivisao = new javax.swing.JButton();
        panelRelatorioEEventos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelSalarioRH = new javax.swing.JLabel();
        labelBonusChefe = new javax.swing.JLabel();
        labelExibirRelatorio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textSalarioRH = new javax.swing.JTextField();
        textBonusChefe = new javax.swing.JTextField();
        comboBoxExibirRelatorio = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        buttonAjustarSalarioRH = new javax.swing.JButton();
        buttonAjustarBonusChefe = new javax.swing.JButton();
        buttonExibirRelatorio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonCadastrar = new javax.swing.JButton();
        buttonImportarXml = new javax.swing.JButton();
        buttonExportarXml = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDepartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelNomeDivisao.setText("Nome da divisão:");

        comboBoxNomeDivisao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxNomeDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNomeDivisaoActionPerformed(evt);
            }
        });

        labelRecursosHumanos.setText("Nome do Recurso Humano:");

        labelPrecoRH.setText("Preço:");

        labelNomeMaquina.setText("Nome da máquina:");

        labelPrecoMaquina.setText("Preço:");

        labelNomeDoChefe.setText("Nome do chefe:");

        labelCustoChefe.setText("Custo:");

        textCustoChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCustoChefeActionPerformed(evt);
            }
        });

        labelBonificacao.setText("Bonificação:");

        botaAddDivisao.setText("+ Divisao");
        botaAddDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaAddDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDepartamentosLayout = new javax.swing.GroupLayout(panelDepartamentos);
        panelDepartamentos.setLayout(panelDepartamentosLayout);
        panelDepartamentosLayout.setHorizontalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomeMaquina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecoMaquina)
                            .addComponent(textPrecoMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomeRecursosHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRecursosHumanos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecoRH)
                            .addComponent(textPrecoRH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDepartamentosLayout.createSequentialGroup()
                            .addComponent(textNomeChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textCustoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textBonificacaoChefe))
                        .addGroup(panelDepartamentosLayout.createSequentialGroup()
                            .addComponent(comboBoxNomeDivisao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaAddDivisao))
                        .addComponent(labelNomeDivisao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDepartamentosLayout.createSequentialGroup()
                            .addComponent(labelNomeDoChefe)
                            .addGap(145, 145, 145)
                            .addComponent(labelCustoChefe)
                            .addGap(35, 35, 35)
                            .addComponent(labelBonificacao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDepartamentosLayout.setVerticalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNomeDivisao)
                .addGap(8, 8, 8)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNomeDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaAddDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecoRH)
                    .addComponent(labelRecursosHumanos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeRecursosHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecoRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeMaquina)
                    .addComponent(labelPrecoMaquina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecoMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeDoChefe)
                    .addComponent(labelCustoChefe)
                    .addComponent(labelBonificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCustoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBonificacaoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        panelRelatorioEEventos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelRelatorioEEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        labelSalarioRH.setText("Salário(RH)        (%):");
        jPanel2.add(labelSalarioRH);

        labelBonusChefe.setText("Bonus(Chefe)    (%):");
        jPanel2.add(labelBonusChefe);

        labelExibirRelatorio.setText("Exibir Relatório: ");
        jPanel2.add(labelExibirRelatorio);

        panelRelatorioEEventos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 70));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1, 0, 5));
        jPanel3.add(textSalarioRH);
        jPanel3.add(textBonusChefe);

        comboBoxExibirRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboBoxExibirRelatorio);

        panelRelatorioEEventos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, -1));

        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 0, 2));

        buttonAjustarSalarioRH.setText("Ajustar Salário");
        buttonAjustarSalarioRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjustarSalarioRHActionPerformed(evt);
            }
        });
        jPanel4.add(buttonAjustarSalarioRH);

        buttonAjustarBonusChefe.setText("Ajustar Bônus");
        jPanel4.add(buttonAjustarBonusChefe);

        buttonExibirRelatorio.setText("Exibir");
        jPanel4.add(buttonExibirRelatorio);

        panelRelatorioEEventos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 70));

        jPanel1.setLayout(new java.awt.GridLayout(12, 1, 0, 2));

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCadastrar);

        buttonImportarXml.setText("Importar XML");
        jPanel1.add(buttonImportarXml);

        buttonExportarXml.setText("Exportar XML");
        jPanel1.add(buttonExportarXml);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRelatorioEEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRelatorioEEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxNomeDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNomeDivisaoActionPerformed
        //preencherCombo();
    }//GEN-LAST:event_comboBoxNomeDivisaoActionPerformed

    public void preencherCombo(){
        comboBoxNomeDivisao.setModel(new DefaultComboBoxModel(divisoes.toArray()));
        //comboBox de String com o nome do livro:

        for (Divisao d : divisoes){
            comboBoxNomeDivisao.addItem(d.getNomeDivisao());
        }
    }
    
    
    private void botaAddDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaAddDivisaoActionPerformed
       new gui.JanelaAdicionarDivisao().setVisible(true);
    }//GEN-LAST:event_botaAddDivisaoActionPerformed

    private void textCustoChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCustoChefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCustoChefeActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        //Add divisao
        divisao.setNomeDivisao(String.valueOf(comboBoxNomeDivisao.getSelectedItem()));
        divisao.add(divisao);
        //iterator.visit(divisao);
        
        //Add RH
        rh.setNomeRH(textNomeRecursosHumanos.getText());
        rh.setCustoRH(Double.parseDouble(textPrecoRH.getText()));
        iterator.visit(rh);
        
        //Add Maquina
        maquina.setNomeMaquina(textNomeMaquina.getText());
        maquina.setCustoMaquina(Double.parseDouble(textPrecoMaquina.getText()));
        iterator.visit(maquina);
        
        //Add Chefe
        chefe.setNomeChefe(textNomeChefe.getText());
        chefe.setCustoChefe(Double.parseDouble(textCustoChefe.getText()));
        chefe.setBonusChefe(Double.parseDouble(textBonificacaoChefe.getText()));
        iterator.visit(chefe);
        
        JOptionPane.showMessageDialog(null, "Recursos, Maquinas e Chefe, cadastrado com sucesso!");
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonAjustarSalarioRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjustarSalarioRHActionPerformed
        
    }//GEN-LAST:event_buttonAjustarSalarioRHActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaAddDivisao;
    private javax.swing.JButton buttonAjustarBonusChefe;
    private javax.swing.JButton buttonAjustarSalarioRH;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonExibirRelatorio;
    private javax.swing.JButton buttonExportarXml;
    private javax.swing.JButton buttonImportarXml;
    private javax.swing.JComboBox comboBoxExibirRelatorio;
    private javax.swing.JComboBox comboBoxNomeDivisao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelBonificacao;
    private javax.swing.JLabel labelBonusChefe;
    private javax.swing.JLabel labelCustoChefe;
    private javax.swing.JLabel labelExibirRelatorio;
    private javax.swing.JLabel labelNomeDivisao;
    private javax.swing.JLabel labelNomeDoChefe;
    private javax.swing.JLabel labelNomeMaquina;
    private javax.swing.JLabel labelPrecoMaquina;
    private javax.swing.JLabel labelPrecoRH;
    private javax.swing.JLabel labelRecursosHumanos;
    private javax.swing.JLabel labelSalarioRH;
    private javax.swing.JPanel panelDepartamentos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRelatorioEEventos;
    private javax.swing.JTextField textBonificacaoChefe;
    private javax.swing.JTextField textBonusChefe;
    private javax.swing.JTextField textCustoChefe;
    private javax.swing.JTextField textNomeChefe;
    private javax.swing.JTextField textNomeMaquina;
    private javax.swing.JTextField textNomeRecursosHumanos;
    private javax.swing.JTextField textPrecoMaquina;
    private javax.swing.JTextField textPrecoRH;
    private javax.swing.JTextField textSalarioRH;
    // End of variables declaration//GEN-END:variables
}
